// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyA-c5gSU4WiVjaHU5bl8m0-KTK4ebxLeaA',
      appId: '1:1056960186687:web:e055aad8b9e8b98b31eb8a',
      messagingSenderId: '1056960186687',
      projectId: 'codemaze-51ffe',
      authDomain: 'codemaze-51ffe.firebaseapp.com',
      storageBucket: 'codemaze-51ffe.firebasestorage.app',
      measurementId: 'G-QJQYQFFDBT',
      databaseURL: 'https://codemaze-51ffe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAznyFtRn5TKRAKAUF8mKN__eLS_cUt5pY',
      appId: '1:1056960186687:android:6a8c9c76e034a97031eb8a',
      messagingSenderId: '1056960186687',
      projectId: 'codemaze-51ffe',
      storageBucket: 'codemaze-51ffe.firebasestorage.app',
      databaseURL: 'https://codemaze-51ffe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBowkh319mXohW61I8eFTb_TLrfvBXis30',
      appId: '1:1056960186687:ios:07437a379d39c36031eb8a',
      messagingSenderId: '1056960186687',
      projectId: 'codemaze-51ffe',
      storageBucket: 'codemaze-51ffe.firebasestorage.app',
      iosBundleId: 'com.example.fypcodemaze',
      databaseURL: 'https://codemaze-51ffe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyBowkh319mXohW61I8eFTb_TLrfvBXis30',
      appId: '1:1056960186687:ios:07437a379d39c36031eb8a',
      messagingSenderId: '1056960186687',
      projectId: 'codemaze-51ffe',
      storageBucket: 'codemaze-51ffe.firebasestorage.app',
      iosBundleId: 'com.example.fypcodemaze',
      databaseURL: 'https://codemaze-51ffe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyA-c5gSU4WiVjaHU5bl8m0-KTK4ebxLeaA',
      appId: '1:1056960186687:web:6fb36707e9036bf231eb8a',
      messagingSenderId: '1056960186687',
      projectId: 'codemaze-51ffe',
      authDomain: 'codemaze-51ffe.firebaseapp.com',
      storageBucket: 'codemaze-51ffe.firebasestorage.app',
      measurementId: 'G-JDGRGDP7Q7',
      databaseURL: 'https://codemaze-51ffe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

}